### ISSUE TITLE
Remove proposal card in Delegation detail page

### ISSUE THREAD

**Issue by junyan233** [metaforo/Realm-Frontinus-House#121]
![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/0eee43fe-75a3-4cbe-93f1-37c818fd38ff)
![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/dda135f0-7a22-4c7c-8df3-d712fbdacc8b)

**Comment by summertapa** [comment]
dupplicated with https://github.com/metaforo/Realm-Frontinus-House/issues/123
