### ISSUE TITLE
Some text format are wrong in the round details 

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#122]
### 1. round 状态标注字体颜色应为黄色  
![256156711-be0aa42e-8cc6-4f31-9a56-09c9a481f878](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/751dbc34-4f29-4779-b4e4-71cdf12d15b1)
![256156762-0939b8f9-6d0b-48ae-8435-1cb8cece1854](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/9707f4f0-7c81-4deb-8aa5-8e7bf19ed806)

**Comment by zhoupufelix** [comment]
fixed and online
