### ISSUE TITLE
UI displaying wrong when the round is not start.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#124]
# 1. delegate round 
 
![256167807-d8e40a5f-f1d3-4bdb-b9eb-0e905bbc9cbe](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/61b6f78b-7560-4dd1-9162-6eb8ffb37271)

**Comment by zhoupufelix** [comment]
fixed and on test-long
