### ISSUE TITLE
Text format displaying wrong after submitted

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#128]
Proposal details 界面显示的文字效果和 编辑器内看到的不一致
（application 也有同样的问题）
https://test-long.metaforo.io/proposal/38
 https://test-long.metaforo.io/application/20
![256173834-74435077-40d0-46cb-9380-45a3434d54f4](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/392968f4-6b67-41b6-a1bc-2bf9e0a38839)
![256174118-c90d78e4-9bf0-4593-b47e-51408d6227d5](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/6a32f0a8-dea5-4382-9759-50f888434b4c)

**Comment by summertapa** [comment]
Comment list 也有同样的问题
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/d17b2e98-1984-4587-93f4-7336200486f9)

**Comment by zhoupufelix** [comment]
fixed and online
