### ISSUE TITLE
FAQ page needs to be removed, and FH Charter should be added.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#130]
FH Charter 指向https://github.com/Calcutatator/Frontinus-House-Docs/blob/main/Charter/Charter.md 

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/f15d2276-45ca-48bf-bfbf-9afdddd554df)

**Comment by zhoupufelix** [comment]
fixed and online
