### ISSUE TITLE
it should fail to submit when the length of title and tldr are not matched the requirement

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#134]
create proposal/applications 界面字体长度不符合要求界面显示红色提示，但点击submit 未被限制提交

 
![256178210-73cf546b-3bfe-46b4-84c7-c34ad0970e19](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/a399dcca-83ab-4c0e-b548-252b280b1769)

**Comment by zhoupufelix** [comment]
fixed and online
