### ISSUE TITLE
When hovering over the Prop deadline, it is difficult to see the end date.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#16]
![252924021-e3ff4f3a-37ae-4c59-abc3-e9ebfe302c41](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/01bc5180-afea-4fa8-8874-fb68929e3188)

**Comment by zhoupufelix** [comment]
fixed and online

**Comment by summertapa** [comment]
显示内容 需要更新一下
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/329abc28-3f4d-4048-a7b8-37cb0de56a4c)

**Comment by zhoupufelix** [comment]
fixed and on test-long

**Comment by summertapa** [comment]
### 1. GMT+8 ；UTC+8 需改成 UTC
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/8d91cec7-b2dc-4abf-a625-d0cab26cf548)
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/21f88a9a-de5f-4efe-ada9-69093ed8607a)


### 2. round list 这边时间需要显示区分上午下午的AM，PM
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/32028547-a98b-4da9-a95e-bd9a3f6b9375)
