### ISSUE TITLE
wrong time format in the comment list

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#174]
### 1. 创建一个新回复，页面显示的时间为年月日。正常情况下应显示just now
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/54243075-048e-46af-94b8-970d64dfc9fa)

**Comment by summertapa** [comment]
还能重现

**Comment by zhoupufelix** [comment]
fixed and on test-long
