### ISSUE TITLE
Popup banner needs to be updated.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#202]
直接访问https://test-long.metaforo.io/create 链接，弹出如下弹框：
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/c48064e4-aa2a-4f22-9692-83135f163df0)

**Comment by summertapa** [comment]
Update: 
直接访问https://test-long.metaforo.io/create 需提示invalid URL 并同时自动跳转回Home 界面

**Comment by ktarun1419** [comment]
hi is this issue still open?

**Comment by summertapa** [comment]
fixed and online
