### ISSUE TITLE
There is a problem with the inserted link redirection.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#208]
填的链接是baidu.com， 没有带http
https://test-long.metaforo.io/proposal/46
 

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/5ef24445-b1ec-49b1-ae9c-dff4b0e642e4)
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/dd59b1b9-5766-4d41-accb-e982d735e9b8)

**Comment by zhoupufelix** [comment]
fixed and online.新插入的都没问题，旧数据已经插入数据库，不管。
