### ISSUE TITLE
A re-submission of a comment should be blocked until the sign request is completed.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#212]
### Description:
 
重现步骤：

1. Comments 界面填写内容的后点击submit button
2. 弹出签名框但未签名
3. 再次点击submit button 出现新的签名提示，按提示完成签名

实际结果： 每次签名都会完成内容提交；点击完成所有待签名（即2次），comment list 出现重复的回复信息

期望结果： 第一次点击submit button 后，按钮应置灰；若用户完成签名，按钮应继续保持置灰状态。若用户cancel 签名请求，submit button 重新高亮可再次操作；

 
### Screenshot:
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/d0a87108-2a27-46a3-b45f-2baeaa313e86)

**Comment by zhoupufelix** [comment]
fixed and online

**Comment by summertapa** [comment]
@zhoupufelix 引入了一个新的问题：取消签名后，再次点击submit并完成签名，内容没有提交成功。comment list 未显示这条回复
