### ISSUE TITLE
 House introduction needs to be updated

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#252]
**改成：**
The Realms Autonomous World (RAW) aims for true autonomy, relying on public goods or infrastructure. This leads to the concept of Frontinus House, a method to fund projects in RAW and the BibliothecaDAO ecosystem. Through funding rounds, innovative projects aligned with Bibliotheca DAO's vision will be supported. Frontinus House aims for transparent, accountable, and collaborative use of public funds, focusing on superior infrastructure catering to the community's needs.
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/9dcbaf95-b565-4853-a9d0-2721f9979360)

**Comment by wliu6v** [comment]
fixed
