### ISSUE TITLE
the font-family of proposal description is not correct 

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#280]
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/413e5801-5985-4103-9757-2e5cf741bce8)

**Comment by summertapa** [comment]
### 2. comment 字体也不正确
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/fbfc2dee-55d0-4c61-b623-1e931d1ebece)

**Comment by zhoupufelix** [comment]
fixed and on test-long
