### ISSUE TITLE
In the proposal round detail page, the right-side card should be updated with a new design.

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#290]
涉及2个卡片：Voting in progress, Voting Ended
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/26149b58-307b-4198-a5c4-1fa8b1e6b8a3)

### 新设计如下
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/a51688da-e152-4bbe-91b9-4b9cf90023d6)
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/2aaf1894-14b3-40e9-b73a-25e1a6ff3163)

**Comment by zhoupufelix** [comment]
fixed and on test-long

**Comment by summertapa** [comment]
Voting ended 卡片也需更新
https://test-long.metaforo.io/52/12345678

**Comment by chenglong-tapatalk** [comment]
我看是新的？
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/69573449/1ff48978-47f9-4000-ba94-0fb6158931af)

**Comment by zhoupufelix** [comment]
fixed and on test-long
