### ISSUE TITLE
should not allow submit proposal again

### ISSUE THREAD

**Issue by junyan233** [metaforo/Realm-Frontinus-House#298]
### Description:
should not allow submit proposal again

提交一次proposal后，不允许再次提交一个

Applications已经做了限制，可以参考，已经提交了，become a delegate变成Already submiited

![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/fb42a74a-6729-4dce-a96c-0ab116f85d33)

**Comment by chenglong-tapatalk** [comment]
新人改了
