### ISSUE TITLE
The last line of the round description is obscured

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#34]
https://test-long.metaforo.io/54/round-3
https://test-long.metaforo.io/delegateDetails/33
 round details 页面上的描述简介最后一行被遮挡 

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/7282dd8a-329f-4f45-80a6-c161a8c98223)

**Comment by summertapa** [comment]
https://stage.frontinus.house/

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/d9f11683-7f8e-4f97-bb88-aaaa9592f21f)

**Comment by zhoupufelix** [comment]
fixed and on test-long
