### ISSUE TITLE
font-family is not matched the design

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#355]
### 1. https://test-long.metaforo.io/56/round-5
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/3f7a9802-b636-4981-9b09-a27609696515)

**Comment by zhoupufelix** [comment]
fixed and on test-long

**Comment by summertapa** [comment]
delegation round 相同的地方也需要改

https://test-long.metaforo.io/delegateDetails/53
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/0b6b92ae-70bd-4a44-9639-7a9d6d625fd1)

**Comment by zhoupufelix** [comment]
fixed and on test-long
