### ISSUE TITLE
background color not same with design

### ISSUE THREAD

**Issue by junyan233** [metaforo/Realm-Frontinus-House#361]
### Description:
background color not same with design

### Screenshot:
![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/e3bd795e-a5dd-411b-9b78-f58bb9acc72a)
![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/fa7abcd4-5b91-44b4-9ffb-2bb427545386)

**Comment by zhoupufelix** [comment]
fixed and on test-long
