### ISSUE TITLE
Should be blocked the next step if the proposal fields didn't filled in Create BIP page

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#465]
必填项未填写的情况下，点击continue/Preview 按钮应提示： All fields must be filled before preview!
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/82519a7a-1da0-4a05-9bb7-7a056eeed1ec)

**Comment by zhoupufelix** [comment]
fixed and on test

**Comment by summertapa** [comment]
更正一下提示 ：  All fields must be filled!

**Comment by zhoupufelix** [comment]
fixed and on test
