### ISSUE TITLE
Vote button of BIP should be changed to text that 'Only Realms NFT holders have permission to vote.' when user wallet didn't have realms NFT

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#473]
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/73663579-767f-4f94-9d14-2cc0a6e22a0b)

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/1e73a1f7-4c67-434a-b9bc-bc19bb236174)

**Comment by zhoupufelix** [comment]
fixed and on test
