### ISSUE TITLE
已经ended状态的proposal，不应该还显示cancel vote入口

### ISSUE THREAD

**Issue by junyan233** [metaforo/Realm-Frontinus-House#512]
### Description:

已经ended状态的proposal，不应该还显示cancel vote入口

### Screenshot:

![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/8bcc4f56-592d-4922-993b-b6560c30db44)

![图片](https://github.com/metaforo/Realm-Frontinus-House/assets/37821776/9f8c52b4-22f1-442b-ab52-6fe419b574c9)

**Comment by summertapa** [comment]
@chaochen83 接口返回错误，这个情况接口应该返回312，而不是311

**Comment by chaochen83** [comment]
修了
