### ISSUE TITLE
Improvement about multi community 

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#680]
1. 其他community 的create delegate, proposal round 界面 下的discord link需要调整
 
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/1221518b-074f-487e-8595-5f6a35aabaa7)
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/46410ef2-5401-41d5-8775-8c454fe4818b)

2. 论坛内页脚也需要按不同论坛来自定义显示 

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/5c0613b8-122c-41fe-92fa-953661674b4e)

3. 不同论坛的 几个页面顶上的导航栏需要显示对应论坛的forum name 

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/78e3a8ae-b8ec-4955-9b69-6e4f0e13f136)

**Comment by chenglong1206** [comment]
3修了 其他的
