### ISSUE TITLE
round details page display Invalid URL error

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#74]
round name:

Use this form to create a new round. Please visit our Discord if you have any questions: https://discord.gg/uQnjZhZPfu.
What is the round name? (Please use only standard letters, no special characters such as dashes or question marks)*
 
![254837582-de7ccbe3-33e4-4537-a199-33b450abd9e2](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/4ccb3fd6-7ad2-48ee-b33e-6522969269f0)
![254837655-3871d61f-c8b2-43f6-bd38-eb48f41eb400](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/d3eb3601-3874-4366-976f-02924244b884)

**Comment by zhoupufelix** [comment]
fixed and on test-long
