### ISSUE TITLE
Comments list does not show the total number

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#82]
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/b16003a8-35bf-4778-a805-1c8f441e8de0)
 
![254847256-a388198e-51d6-4e3b-8b0f-c262d49287cc](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/7397b076-541a-4e2c-a540-e3323a523df4)

**Comment by summertapa** [comment]
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/856c85c5-f3c5-4918-876a-cee03f60ad21)

**Comment by zhoupufelix** [comment]
fixed and online

**Comment by summertapa** [comment]
Application 详情页下也缺少comment 统计数
https://test-long.metaforo.io/application/19
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/b71f26ed-247e-4bb5-a36d-6d98d168c4b6)

**Comment by zhoupufelix** [comment]
fixed and on test-long
