### ISSUE TITLE
The reply function should be turned off when the proposal Round has ended

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#84]
proposal Round 已结束的情况下应关闭回复功能 （参考prop house的 回复框关闭效果，或者点击submit 的时候提示Round has been closed. Cannot create comment.）

 **application 详情页下的commnet list 也有同样的问题**
![254848090-df861efe-c1c5-4535-87ab-b9f3cc9bfa8c](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/322292f9-63e1-49fe-81e8-62f373be2d28)

![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/ff3c8a0d-434a-4912-84fc-682877aa1b37)

**Comment by zhoupufelix** [comment]
fixed and on test-long
