### ISSUE TITLE
the font effect and statistics display of the currently selected tab are inconsistent with the design

### ISSUE THREAD

**Issue by summertapa** [metaforo/Realm-Frontinus-House#99]
House 主页中的导航栏功能切换，当前选中tab 的字体应为黄色 House 主页中的导航栏功能切换，当前选中tab 的字体效果和 统计数显示与设计不一致
 
 
![image](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/60417b84-1793-4f04-a313-b84fa5ddb714)

**设计图如下：**
![255456993-9f7612c1-c796-4544-a93e-57c3e00129e0](https://github.com/metaforo/Realm-Frontinus-House/assets/13515182/d914cef6-2c97-48f4-9b31-7fb0188c6779)

**Comment by chenglong-tapatalk** [comment]
delegate数量炳轩会加 样式已经调了
